version: "3.9"

services:

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./postgre/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./ Dockerfile
  #   container_name: backend
  #   command: sh -c 
  #   volumes:
  #     - ./core:/uer/src/app
 
   
  #   # env_file:
  #   #   - ./envs/dev/.env
    
  #   environment:
  #     - SECRET_KEY=test
  #     - DEBUG=True
  #     - COMINGSOON=False
  #     - SHOW_DEBUGGER_TOOLBAR=True
  #     - ENABLE_DEBUGPY=True
  #   restart: always

