# Generated by Django 4.2.11 on 2024-04-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_skillmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinformationmodel',
            options={'ordering': ['age']},
        ),
    ]
