# Generated by Django 4.2.11 on 2024-04-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_photomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
